# Generated by Django 4.2.3 on 2023-08-08 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0003_completed_reaction_completedreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedreport",
            name="completed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="community.completed",
            ),
        ),
    ]
