# Generated by Django 4.2.3 on 2023-08-09 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0003_comment_commentreport"),
        ("community", "0005_alter_postimage_post"),
    ]

    operations = []
