# Generated by Django 4.2.3 on 2023-08-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0007_alter_postimage_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="view_cnt",
            field=models.IntegerField(default=0),
        ),
    ]
