# Generated by Django 4.2.3 on 2023-08-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0008_post_view_cnt"),
    ]

    operations = [
        migrations.AddField(
            model_name="completed",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
