# Generated by Django 4.2.3 on 2023-08-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0009_completed_is_private"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="exercises",
        ),
        migrations.RemoveField(
            model_name="post",
            name="purposes",
        ),
        migrations.AddField(
            model_name="post",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="community.exercise",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="purpose",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="community.purpose",
            ),
        ),
    ]
