# Generated by Django 4.2.3 on 2023-08-11 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0010_banner"),
        ("community", "0010_remove_post_exercises_remove_post_purposes_and_more"),
    ]

    operations = []
