# Generated by Django 4.2.3 on 2023-08-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0011_merge_20230811_0053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[("ORDINARY", "ORDINARY"), ("PRO", "PRO")],
                default="ORDINARY",
                max_length=20,
            ),
        ),
    ]
