# Generated by Django 4.2.3 on 2023-08-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilereport',
            name='content',
        ),
        migrations.AlterField(
            model_name='profilereport',
            name='reason',
            field=models.CharField(max_length=50),
        ),
    ]
