# Generated by Django 4.2.3 on 2023-08-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="type",
            field=models.CharField(
                choices=[
                    ("COMMON", "COMMON"),
                    ("DOCTOR", "DOCTOR"),
                    ("TRAINER", "TRAINER"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="profilereport",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="accounts.profile",
            ),
        ),
    ]
