# Generated by Django 4.2.3 on 2023-08-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_profile_type_alter_profilereport_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="intro",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
