# Generated by Django 4.2.3 on 2023-08-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_profilereport_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="intro",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="type",
            field=models.CharField(
                choices=[
                    ("COMMON", "COMMON"),
                    ("DOCIOR", "DOCTOR"),
                    ("TRAINER", "TRAINER"),
                ],
                max_length=15,
            ),
        ),
    ]
