# Generated by Django 4.2.3 on 2023-08-14 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_intro"),
        ("accounts", "0003_profile_completed_cnt"),
    ]

    operations = []
