FROM python:3.8

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

RUN python manage.py collectstatic --noinput

RUN chmod -R 755 /app/static /app/media

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "backback.wsgi:application"]
