# Generated by Django 4.2.3 on 2023-08-05 15:50

from django.db import migrations, models
import gym.models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gym.models.image_upload_path),
        ),
    ]
