# Generated by Django 4.2.3 on 2023-08-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_gym_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
