# Generated by Django 4.2.3 on 2023-08-07 21:48

from django.db import migrations, models
import gym.models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0002_rename_longiude_gym_longitude_remove_gym_machines_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gym",
            name="info",
            field=models.JSONField(default=gym.models.defalt_info),
        ),
    ]
