# Generated by Django 4.2.3 on 2023-08-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0003_alter_gym_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gym",
            name="key",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
