# Generated by Django 4.2.3 on 2023-08-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_gym_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gym.gym'),
        ),
    ]
